"""initial

Revision ID: 143a57a7c33f
Revises: 
Create Date: 2025-09-01 02:10:31.880376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143a57a7c33f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_level_title'), 'level', ['title'], unique=True)
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prize',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prize_title'), 'prize', ['title'], unique=True)
    op.create_table('level_prize',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('prize_id', sa.Integer(), nullable=False),
    sa.Column('received', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.ForeignKeyConstraint(['prize_id'], ['prize.id'], ),
    sa.PrimaryKeyConstraint('level_id', 'prize_id')
    )
    op.create_table('player_level',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id', 'player_id', 'level_id')
    )
    op.create_index(op.f('ix_player_level_id'), 'player_level', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_level_id'), table_name='player_level')
    op.drop_table('player_level')
    op.drop_table('level_prize')
    op.drop_index(op.f('ix_prize_title'), table_name='prize')
    op.drop_table('prize')
    op.drop_table('player')
    op.drop_index(op.f('ix_level_title'), table_name='level')
    op.drop_table('level')
    # ### end Alembic commands ###
